### ISSUE TITLE
javaCheck does not recognize OpenJDK

### ISSUE THREAD

**Issue by jkl445** [dojo/cli-test-intern#103]
**Bug**

When running functional tests, the Java checker does not recognize OpenJDK installations. The output of java -version does not contain the substring "java version" but instead shows "openjdk version ...".

Package Version: 0.5.1

**Actual behavior:**

```
> dojo test -f
Error! Java VM could not be found.
A Java VM needs to be installed and available from the command line to allow the dojo test command to run tests in a browser locally or remotely.
```

```
> java -version
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (IcedTea 3.7.0) (build 1.8.0_161-b12 suse-1.1-x86_64)
OpenJDK 64-Bit Server VM (build 25.161-b12, mixed mode)
```

**Comment by dylans** [comment]
@jkl445 thanks, if you have a time for a PR that would be great, if not we'll try to get to this asap.
