### ISSUE TITLE
Functional tests don't seem to work on Windows.

### ISSUE THREAD

**Issue by tomc974** [dojo/cli-test-intern#106]
**Bug** 

Package Version: `@dojo/cli-test-intern@2.0.0` with `intern@4.2.0`

When running the command `dojo build -m test && dojo test -c local -f` with the following test file, it works as expected on Linux but doesn't work on Windows. On Linux, you can see a browser window being opened and broken tests being marked as failed. On Windows, the application reports `testing completed successfully` even though there are broken tests, no browser window is opened.

**Code**

```typescript
const { describe, it } = intern.getInterface('bdd')
const { expect } = intern.getPlugin('chai')

describe('Home page', function() {
    it(
      'should display',
      function() {
        return this.remote
          .get('http://localhost:9000/')
          .findByTagName('header')
          .findByTagName('footer')
          .end()
      }
  )
})
```

**Expected behavior:**

Functional tests should be run and there results reported by the application.

**Actual behavior:**

The application reports `testing completed successfully` even though no tests were run.

**Comment by agubler** [comment]
I've has test the latest release of `cli-build-app` and `cli-test-intern` on windows and the functionals seemed to run as expected.
