### ISSUE TITLE
Update version of source-map, remove @types reference

### ISSUE THREAD

**Issue by dylans** [dojo/cli-test-intern#107]
New versions of source-map include their own type definitions, so we can remove our dependency on type definitions if we update to a new version of source-map:

```
npm WARN deprecated @types/source-map@0.5.7: This is a stub types definition for source-map (https://github.com/mozilla/source-map). source-map provides its own type definitions, so you don't need @types/source-map installed!
```

**Comment by matt-gadd** [comment]
I think this is just a superfluous `@type`'s dependency as far as I can tell, so this can just be removed.
