### ISSUE TITLE
`dojo test` fails for projects with multiple bundles

### ISSUE THREAD

**Issue by agubler** [dojo/cli-test-intern#17]
**Bug**

`dojo test` fails if the project has multiple bundles (tested with the [auto bundling](https://github.com/dojo/cli-build/pull/89) only).

Error:

```
⠴ Running testsReferenceError: window is not defined
  at <_build/tests/unit/webpack:/webpack/bootstrap 606e39ae41b6b3349607:2:0>
  at <_build/tests/unit/all.js:153:10>
  at executeModule  <node_modules/@dojo/loader/loader.ts:680:52>
  at <node_modules/@dojo/loader/loader.ts:668:10>
  at Array.map  <native>
  at executeModule  <node_modules/@dojo/loader/loader.ts:662:43>
  at <node_modules/@dojo/loader/loader.ts:749:5>
  at guardCheckComplete  <node_modules/@dojo/loader/loader.ts:734:2>
  at checkComplete  <node_modules/@dojo/loader/loader.ts:741:25>
  at onLoadCallback  <node_modules/@dojo/loader/loader.ts:822:4>
 failed Running tests
```

Repo for reproducing the error isolation here: https://github.com/agubler/-dojo-test-bug-repro

Checkout `failing` branch, `npm i`, `dojo test` (assumes @dojo/cli is installed globally)

Diff between master and failing: https://github.com/agubler/-dojo-test-bug-repro/compare/failing

**Comment by edhager** [comment]
I have two pull requests that resolve this ticket.  One is on dojo/cli-build and the other is in dojo/cli-test-intern.

**Comment by agubler** [comment]
The tests actually fail for the repro example when using multiple bundles, so there still seems to be an issue even with these changes.

Having discussed with @matt-gadd, we were thinking that we should just disabled the bundling for testing (ie. when the `--with-tests` flag is passed to `cli-build`)
