### ISSUE TITLE
`dojo test -c local` fails

### ISSUE THREAD

**Issue by kitsonk** [dojo/cli-test-intern#18]
**Bug**

Running `dojo test -c local` which is the implied configuration according to the documentation fails to work properly.

Package Version: master

**Code**

```sh
dojo test -c local
```

**Expected behavior:**

Test complete successfully.

**Actual behavior:**

```
⠸ Running testsError: Failed to load module /Users/kitsonk/github/examples/todo-mvc/node_modules/@dojo/cli-test-intern/intern/intern-local.js from /Users/kitsonk/github/examples/todo-mvc/node_modules/@dojo/cli-test-intern/intern/intern-local.js (parent: *20)
  at ReadFileContext.callback  <node_modules/dojo/loader.ts:831:119>
  at FSReqWrap.readFileAfterOpen [as oncomplete]  <fs.js:365:13>
 failed Running tests
Tests did not complete successfully
```

**Comment by jacobroufa** [comment]
I have addressed this issue in #45.

I thought about setting the config argument to load `intern.js` if the "default argument" `local` is passed in, but that seemed smelly, so I ended up just changing the name of the file to `intern-local.js` and have ensured that the same test suite runs whether the command `dojo test` or `dojo test -c local` is executed.

Please let me know if there's anything else to address in the scope of this issue!
