### ISSUE TITLE
Customising to the Intern Configuration

### ISSUE THREAD

**Issue by kitsonk** [dojo/cli-test-intern#30]
**Enhancement** 

Related to #21 

There are several common use cases that would fall outside of the "default" configuration options we currently offer with intern.  We need to figure out how to support these in a way that would not simply lead a user to `eject` the CLI command and go it their own.

Use cases we don't currently support, but are highly likely:

- Changing the types of browsers and version to run against remotely for SauceLabs, BrowserStack and TestingBot.
- Saving authentication information so they don't have to be passed on the CLI.
- Changing the local SeleniumTunnel to support Safari or Firefox instead of Chrome.
- Supporting proxy only configurations (but see #24)
- Changing the concurrency of remote tunnels.

**Comment by agubler** [comment]
Allowing a custom intern configuration is outside the goals of the cli-test-intern command. If a consumer needs something outside the provided intern configuration it is recommended to either eject or fork the command and publish with the required customisations.
