### ISSUE TITLE
Allow `disableLazyWidgetDetection` to be configured

### ISSUE THREAD

**Issue by mwistrand** [dojo/cli-test-intern#36]
**Bug**

When the `build` command is executed, it automatically sets `disableLazyWidgetDetection` to `true`, which is not desirable in applications that lazy-load widgets since it results in the tests being unable to load those widgets (e.g., dojo/cli-build#106).

The expected behavior is that executing `dojo test` would use the same `disableLazyWidgetDetection` flag used when running `dojo build`.

**Comment by matt-gadd** [comment]
@mwistrand I don't believe this is a valid bug. All module bundling should be sync when in tests for convenience, and disabling the flag shouldn't result in widgets not being able to load.

**Comment by mwistrand** [comment]
All bundling is synchronous but widgets still may contain `load(require, './widgets/MyWidget')`, which is not parsed with `disableLazyWidgetDetection: true`. So even though the test may pull in `MyWidget` directly, the `load` call still has no idea which webpack module ID `'./widgets/MyWidget' is supposed to map to.
