### ISSUE TITLE
Intern config is misleading

### ISSUE THREAD

**Issue by kitsonk** [dojo/cli-test-intern#38]
**Bug**

The Intern configurations included with `cli-test-intern` contain a lot of information that is not actually used, like the loader configuration.  This is because the tests are actually run against a WebPack bundle and therefore there is not an AMD loader impacted.

End users might get confused by this configuration.  We should only have configuration in the files that is actually used by Intern when running under WebPack.

**Comment by rorticus** [comment]
This is going to be addressed via the intern 4 changes!
