### ISSUE TITLE
Integrate @dojo/test-extras

### ISSUE THREAD

**Issue by kitsonk** [dojo/cli-test-intern#39]
**Enhancement**

We should integrate `@dojo/test-extras` so that it is available by _default_ when testing.

**Comment by kitsonk** [comment]
We should also add the `loadJsdom` module to the intern configurations so it is available by default.

**Comment by agubler** [comment]
@kitsonk I think that it is available by default when `cli-test-intern` is installed and jsdom loaded by default - https://github.com/dojo/cli-test-intern/blob/master/src/intern/intern.js#L52.

Unless you were thinking about something more sophisticated 😄

**Comment by kitsonk** [comment]
It apparently was resolved before the issue was opened.

Resolved by #34 and #37
