### ISSUE TITLE
JDK Dependency

### ISSUE THREAD

**Issue by eheasley** [dojo/cli-test-intern#51]
`cli-test-intern` currently defaults to using selenium tunnel for functional tests, which requires the JDK.  We either need to deal with this better or at least note it as part of `cli-test-intern` in some way.

**Comment by vansimke** [comment]
This came up as an issue because I user didn't have the JDK installed and tried to run `dojo test -b...`. Since the browser tests use the Selenium tunnel, this appears to be a Dojo error. Lacking documentation, it could surprise users that they need the JDK when Dojo 2 normally only depends on other JS libraries.

**Comment by kitsonk** [comment]
There doesn't seem to be an easy way of detecting this when installing from npm.  In theory, the CLI command could detect this, but also it is arguable that DigDug should be helping with this, and so have opened theintern/digdug#48 as well.

**Comment by edhager** [comment]
Below is a node script that could be used to detect if java is installed or not.  We could add something like that as a post install script in package.json or the cli command could use it as a check each time the command runs.  

@kitsonk thoughts?

```javascript
const { exec } = require('child_process');

let found = false;
function noJava() {
	console.log('Java could not be detected.');
}

const javaVersion = exec('java -version', (err, stdout, stderr) => {
	if (err) {
		noJava();
	} else {
		let responseString = '';
		stdout && (responseString += stdout.toString());
		stderr && (responseString += stderr.toString());

		const pos = responseString.indexOf('java version');
		if (pos >= 0) {
			const version = responseString.slice(pos).split('\n')[0].split(' ')[2];
			console.log(`Detected Java version ${version}`);
			found = true;
		} else {
			noJava();
		}
	}
});

javaVersion.on('close', () => {
	process.exit(found ? 0 : 1);
});
```

**Comment by kitsonk** [comment]
That sounds like a good idea, of course modifying it to make sense in the usability of the command (which is essentially just warning people that they will not be able to run local tests without installing Java)  I think @umaar ran into it too and got a bit frustrated and might have a comment about what would make good ergonomics on this.
