### ISSUE TITLE
Show browser URL when tests fail

### ISSUE THREAD

**Issue by vansimke** [dojo/cli-test-intern#60]
Running `dojo test` displays a URL that can be used to run the tests in a web browser, but only when all  of the tests pass. When at least one fails, the URL is not displayed. The URL should be displayed whether or not the tests pass.

**Comment by matt-gadd** [comment]
this was fixed in https://github.com/rorticus/cli-test-intern/commit/9ffc1b19b3122ddaa8c27480f007cf13050c9c96
