### ISSUE TITLE
dojo test --functional also runs unit tests

### ISSUE THREAD

**Issue by JamesMilnerUK** [dojo/cli-test-intern#62]
**Bug**

When you run functional tests from the CLI it runs the unit tests also (which the dojo-test-intern believe fail)

**Package Version**: 2.0.0-beta2.4

**Code**

```dojo test --functional ```

**Expected behavior:**

The CLI to just functional tests, i.e. ones in `tests/functional/all.ts`

**Actual behavior:**

Runs both functional and unit tests, and the unit tests are treated as functional test and in turn fail.

**Screenshot**
![screenshot_20171001_194602](https://user-images.githubusercontent.com/8822075/31057847-35e6851a-a6e1-11e7-8173-f77c89d8a56a.png)

**Comment by kitsonk** [comment]
Related to #21.

The whole thing is a bit counter intuitive at the moment.  I think we were thinking we would clean it up when we go to Intern 4.
