### ISSUE TITLE
"To run in browser" message is confusing

### ISSUE THREAD

**Issue by edhager** [dojo/cli-test-intern#68]
I'm using the 0.2.0 version of cli-test-intern.

When I run "dojo test", the last message output to the console is:  

> to run in browser: http://localhost:8080/node_modules/intern/?config=node_modules/@dojo/cli-test-intern/intern/intern.json

There is no server running so that URL is not going to work.

**Comment by kitsonk** [comment]
Also, the URL is quite wrong for Intern 4, which is what is in master.

**Comment by kitsonk** [comment]
Refs #38 in that a lot of the output/options are confusing and misleading.
