### ISSUE TITLE
"local" config does not exist.

### ISSUE THREAD

**Issue by edhager** [dojo/cli-test-intern#69]
I'm using version 0.2.0 of cli-test-intern.

When I run "dojo test -h", I see this:

```
-c, --config       Specifies what configuration to test with:
                   'local'(default), 'browserstack', 'testingbot', or
                   'saucelabs'.                     
```

"local" is not a valid configuration in https://github.com/dojo/cli-test-intern/blob/master/src/intern/intern.json.  So if  you try to use it:

> dojo test -c local

you get an error:
```
Error: Unknown child config "local"
  at <src/lib/common/util.ts:108:13>
  at Array.forEach  <anonymous>
  at mixinConfig_1  <src/lib/common/util.ts:105:13>
  at <src/lib/common/util.ts:139:4>
  at <node_modules/intern/node_modules/@dojo/core/async/Task.ts:319:12>
  at handler  <node_modules/intern/node_modules/@dojo/core/async/ExtensiblePromise.ts:216:14>
  at <anonymous>

  testing failed
```

Also, in the Dojo 2 projects, we use "local" to mean "run the tests in a browser (Chrome) using a local instance of Selenium".  

Can we change the help text to indicate that the absence of a "config" option will cause the tests to run locally in node? Or change "local" to "node" in the help text and make it trigger the default behaviour?

**Comment by edhager** [comment]
I didn't see #38.  This would fall into that category.

**Comment by agubler** [comment]
This now works, `dojo test -c local` runs the tests locally as expected.
